# Generated by Django 3.0.8 on 2020-08-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pelayanan', '0014_auto_20200806_1100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengaduan',
        ),
    ]
